### ISSUE TITLE
Clarification of the Specifications for Map

### ISSUE THREAD

**Issue by m4ttr4ymond** [tsender/eecs545_artificial_curiosity#2]
# Clarification about the Trello card
- `clean_directions(self, coordinates: List[Tuple[int, int], ...])`
    - `coordinates: List[Tuple[int, int], ...]`: gives a list of coordinates that should be checked to make sure the model can move there without its FOV going off the map. **This means that if the `fov` is x, the rover should remain at least `x` pixels away from the edge so that the `fov` does not go over the edge.**

Also, if the rover does go over the edge or get closer than `fov` pizels to the edge, the `Map` should throw an error when `get_fov` is called so we can catch it before it propagates.

**Comment by aravind1338** [comment]
Fixed. I'll add a README later with visual aids to show what's been implemented in Map (legal pixels and the grains that are found)

**Comment by m4ttr4ymond** [comment]
Thanks @aravind1338 :)
